- README.md
- src/commands/new.ts
- src/lib/help.ts
- src/template/package.json
- src/template/tasks/example-custom-logic.js
- src/template/tasks/example-lcd-client-extra.js
- src/template/tasks/example-with-lib.js
- src/template/tasks/template.js
Looking through code, found some refs to iboss repo
> removed missing license and more iboss to terra-money edits

- README.md
- src/config.test.ts
As there are many devs using our tools with NodeJs 17 here are some instructions on setting up the environment before running terrain. When the https://github.com/bitcoinjs/bip32/issues/59#issue-1192815210 is fixed we will update all dependencies to do not have any workaround.
> Doc how to run the Node env

- README.md
Changed localterra version 0.5.2 to 0.5.17
> More recent LocalTerra version

- src/commands/contract/updateAdmin.ts
- src/lib/deployment.ts
- src/lib/waitForInclusionBlock.ts
tsc -b is currently throwing a couple of errors, with these changes no errors are reported.
> refactor: Fix potential issues with undefined values and add types to waitForInclusionInBlock

- README.md
- src/template/lib/index.ts
- src/template/package-lock.json
When prepack is executed some TS errors appears because of missing return type from lib/index.ts and dependencies install into the template which this PR fixes.
> fix: prepack due TS compilation error

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Move pull_request_template.md to the correct folder
> feat: pull request templates

- package.json
- src/template/package.json
Included "overrides" parameter in the template/package.json file.  Frontend updates are now immediately reflected in the application.
Changes in root package.json file due to ordering and formatting.  No functional changes implemented.
> fix: stop crash when frontend is updated

- src/template/package.json
Reverting react-error-overlay override.
> revert: frontend react-error-overlay override

- README.md
- package-lock.json
- package.json
- src/commands/contract/new.ts
- src/lib/LCDClientExtra.ts
- src/lib/deployment.ts
This will add TerraV2 comptaibility
> feat: terra v2 compatibility

- src/commands/task/new.ts
Related issue https://github.com/terra-money/terrain/issues/88
> fix(terrain): new task

- README.md
- src/commands/contract/new.ts
- src/commands/new.ts
Instead of replacing the values that can create confusion for the users is better to throw an error as defined here
> feat: error on workspace creation with regex on name

- src/commands/console.ts
Prevents a ton of errors when building Terrain with TSC.
> build: Don't double transpile any source

- README.md
- src/commands/contract/build.ts
- src/commands/contract/migrate.ts
- src/commands/contract/optimize.ts
- src/commands/deploy.ts
- src/commands/new.ts
- src/lib/deployment.ts
- src/lib/env.ts
- src/lib/flag.ts
- src/lib/useARM64.ts
A few updates here: 
* Remove arm64 flag and detect architecture automatically. 
* Fix template replacement for crate names. 
* Remove optimize flag from build command.
> feat: Detect arm64 arch automagically.

- src/commands/wallet/new.ts
Small update, when testing a dapp it's useful to have a bunch of new addresses.
> feat: Print address of generated wallet.

- README.md
Updating README header styling and button links.
> docs: update readme header

- src/lib/deployment.ts
Aarch64 wasm binary files may be stored on LocalTerra or testnet, however, attempting to store them on mainnet will lead to an error for the user.  If the user attempts to store an aarch64 wasm on mainnet, terrain will now automatically rebuild and reoptimize the contract as a default wasm file for storage.
> fix: avoid storing aarch64 wasm on mainnet

- package-lock.json
- package.json
Make it easier for development by running `npm run watch`.
> build: Add watch command.

- README.md
Conveying updated functionality:
- npm install commands are now automatically executed upon app generation.
- contract names mirror app names.
Providing further clarifications for step-by-step deployments, migrating CosmWasm contracts, and utilizing Terrain main branch locally.
> docs: Updating README.md

- package-lock.json
- packages/cosmwasm-typescript-gen/package.json
- packages/cosmwasm-typescript-gen/src/commands/generate.ts
- packages/cosmwasm-typescript-gen/src/generate.ts
- packages/cosmwasm-typescript-gen/src/utils.ts
- packages/wasm-ast-types/package.json
- packages/wasm-ast-types/src/types.ts
- packages/wasm-ast-types/src/utils/types.ts
- packages/wasm-ast-types/src/wasm.ts
- packages/wasm-ast-types/tsconfig.json
- packages/wasm-ast-types/types/messages.d.ts
- packages/wasm-ast-types/types/types.d.ts
- packages/wasm-ast-types/types/utils/babel.d.ts
- packages/wasm-ast-types/types/utils/index.d.ts
- packages/wasm-ast-types/types/wasm.d.ts
- src/index.ts
- src/lib/generateClient.ts
CosmWasm 1.1 introduces a new structure for contract schema and this PR adds support for the new format. 
The main differences are: 
* All JSON Schema files are now combined into one. 
* Response types are defined with a new macro which makes matching types to queries much easier.
> feat: TypeScript generation for CosmWasm 1.1.

- README.md
- src/commands/contract/schema.ts
Adding `terrain contract:schema` command.
> feat: schema command

- src/TerrainCLI.ts
- src/commands/new.ts
Updating the output after executing `terrain new`
> style: terrain new output

- .prettierrc
- package-lock.json
- package.json
- src/TerrainCLI.ts
- src/commands/contract/build.ts
- src/commands/contract/generateClient.ts
- src/commands/contract/instantiate.ts
- src/commands/contract/new.ts
- src/commands/contract/optimize.ts
- src/commands/contract/store.ts
- src/commands/deploy.ts
- src/commands/new.ts
- src/commands/wallet/new.ts
- src/lib/deployment.ts
- src/lib/runCommand.ts
- src/lib/signer.ts
- src/types.d.ts
- Adding next steps logging for terrain commands by including a `successMessage` function as an argument to the `runCommand` function.
- Improving error logging for Terrain and even actionable advice to include terminal hyperlinks!
- Updating the `.prettierrc` file to standardize code formatting for the better.  Feedback is appreciated.
https://user-images.githubusercontent.com/30275692/199309352-16c5199a-5ea1-4d3d-91aa-f94cf593daec.mov
> feat: contract command steps
