terra-money/terrain

src/lib/deployment.ts
When deploying larger contracts it's possible to get out of gas errors. instead of hardcoding these values we can let Terra.js estimate the required gas for us.
This also means there's some outdated gas config values in config.terrain.json, but this is a more urgent issue I'd like to get fixed asap.
=> fix: Enable automatic gas calculation

src/commands/task/run.ts, src/lib/deployment.ts
Updated task runner and build commands to inherit environment variables.
This resolves the following issue : https://github.com/iboss-ptk/terrain/issues/28
=> feat: adding inheritance of environment variables to tasks and builds

src/lib/deployment.ts
This PR fix the build process for `npx terrain deploy counter --signer validator` due breaking changes related the [cosmwasm/rust-optimizer:0.12.3](https://hub.docker.com/layers/rust-optimizer/cosmwasm/rust-optimizer/0.12.3/images/sha256-a1b389c185bfa11fb224d2b7faf856f3550753fd895221464644b41cd78c7763?context=explore) using cargo 1.55 with the following error log:
```
Building contract in /code ...
Downloading crates ...
error: failed to download `uint v0.9.3`
Caused by:
unable to get packages from source
Caused by:
failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.9.3/Cargo.toml`
Caused by:
feature `edition2021` is required
The solution is to check the docker image rust-optimizer:0.12.3 (validate that cargo version is 1.55) and upgrade to the …
```
=> chord: update rust optimizer

bin/run
Following the guide here: https://oclif.io/docs/error_handling
I was able to write a global error handler that will append additional information about an error if the error contains a response with a message. 
```
using pre-baked 'test1' wallet on localterra as signer
updating contract admin to: terra1dz9kket573z55syas2nw93vkde3mytwx6l64rp... !
Error: Request failed with status code 400
```
```
using pre-baked 'test1' wallet on localterra as signer
updating contract admin to: terra1dz9kket573z55syas2nw93vkde3mytwx6l64rp... !
Error: Request failed with status code 400
Response: failed to execute message; message index: 0: unauthorized: invalid request
```
Notice the extra `Response:` which provides necessary info for debugging.
=> feat: Append response from LCD if one exists in Error object.

src/commands/deploy.ts, src/lib/deployment.ts, src/template/config.terrain.json
During the Ottawa hackathon we heard feedback that the deploy process was slow and painful when using m1 hardware. This is due to the emulation used when running rust-optimizer. So we should include a new flag, `--arm64` that will let the developer use `rust-optimizer-arm64` when appropriate, but builds produced should only be used during development. 
From the readme of rust-optimizer: 
> However, the native Arm version produces different wasm artifacts than the Intel version. Given that that impacts reproducibility, non-Intel images and build artifacts contain a "-arm64" suffix, to differentiate and flag them.
> Arm images are released to ease development and testing on Mac M1 machines. For release / production use, only contracts built with the Intel optimizers must be used.
=> feat: Add --arm64 flag which will use rust-optimizer-arm64 for optimization. 

src/commands/contract/updateAdmin.ts
New command to update the admin of an already deployed contract. 
This is useful for moving ownership of a contract to a new multisig wallet. 
First deploy your contract, make sure you use `--set-signer-as-admin` to set an admin address for the contract. 
```
> terrain deploy cw20-blocklist --signer test1 --set-signer-as-admin
```
Then you can update the admin to a new address: 
```
> terrain contract:updateAdmin cw20-blocklist terra1dz9kket573z55syas2nw93vkde3mytwx6l64rp --signer test1
using pre-baked 'test1' wallet on localterra as signer
updating contract admin to: terra1dz9kket573z55syas2nw93vkde3mytwx6l64rp... done
- events:
- type: message
attributes:
- key: action
value: /terra.wasm.v1beta1.MsgUpdateContractAdmin
- key: module
value: wasm
- type: update_contract_admin
attributes:
- …
```
=> feat: New contract:updateAdmin command.

README.md
Description:
This is an addendum to the README.md for an error that occured on a Macbook M1. The docker command failed after attempting to update the crate.io index. Adding --arm64 flag helped progress the operation.
=> Update README.md with M1 fix

README.md, src/commands/wallet/new.ts
This PR will:
- Add `wallet:new` command for generating new terra wallets
It outputs to `stdout` by default, but it can be given the flag `--outfile=<path>` to store the mnemonic there instead.
Close #39
=> feat: add wallet:new command

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/pull_request.md
Create bugfix request, feature request and pull request templates to standardize the way information reaches the development team and community
=> feat(templates): bug, feature and pull request

src/lib/deployment.ts
On deployment the following script tries to access "cargo.toml" instead of "Cargo.toml" which produces the following error:
$ terrain deploy token-factory --signer test --network testnet
Error: ENOENT: no such file or directory, open './cargo.toml'
Changing the file name to uppercase is the solution for this error
=> fix: typo cargo.toml -> Cargo.toml

src/commands/contract/migrate.ts
Migrate won't work without a contract supplied: 
```
terrain contract:migrate --signer pisco --network testnet   
Error: ENOENT: no such file or directory, chdir '~/GitHub/terra-dapp' -> 'contracts/undefined'
Code: ENOENT
```
After: 
```
terrain contract:migrate --signer pisco --network testnet  
›   Error: Missing 1 required arg:
›   contract
›   See more help with --help
```
=> fix: Make contract argument required for migrate command.

.eslintrc.js, README.md, src/commands/contract/instantiate.ts, src/commands/contract/migrate.ts, src/commands/contract/store.ts, src/commands/contract/updateAdmin.ts, src/commands/deploy.ts, src/commands/task/run.ts, src/commands/wallet/new.ts, src/config.ts, src/lib/LCDClientExtra.ts, src/lib/deployment.ts, src/lib/env.ts, src/lib/flag.ts
This PR includes a few features/improvements.
1. The ability to call storeCode and instantiate from inside of tasks. I've added an example to the readme which can be viewed here: https://github.com/terra-money/terrain/blob/de5627172ec60da427c7abd5ae6721fa60051087/README.md#creating-tasks
2. Moving reused flags to `src/lib/flag.ts`. There were situations where flags are reused, but the description or default was different depending on the command. In these situations we can move the flag to this new file, import it, and reference the same default value and description.
3. Added a default value for `--signer`. When using LocalTerra, we can assume the signer will be the `test1` wallet. This improves usability for local development. 
4. I ran the readme generator which overwrote some of the …
=> feat: Automate deployments through tasks! 

src/lib/deployment.ts
Since the new version of the chain renamed the event with instantiate when recovering the contract address we also should do the same with terrain otherwise the deployment flow fails with the following error code:
```
instantiating contract with code id: 1... done
TypeError: Cannot read properties of undefined (reading 'attributes')
```
=> fix(instantiate): new contract

src/commands/task/run.ts
As pointed out in #100 the current version of Terrain is too strict on the tasks. Registering the ts-node project with transpile-only focuses on just converting the code to JavaScript which seems more appropriate. 
Closes #100
=> fix: Use transpile-only when running tasks.

package-lock.json, package.json, src/commands/contract/generateClient.ts, src/commands/new.ts, src/lib/capitalize.ts
While running through the tutorial for Terrain in our docs I ran into the following error: 
```
➜  my_terra_dapp terrain console
Error: Cannot find module './clients/My_terra_dappClient'
```
Turns out just capitalizing wasn't enough, it needs to be PascalCase to remove underscores. After these changes everything is running smooth: 
```
➜ terrain console
terrain > await lib.increment();
{
txhash: '00F29472EE973B678F3CC23A26751C4B7B45E3CE7D2973AE78E6A328B362278A',
raw_log: '[{"events":[{"type":"execute","attributes":[{"key":"_contract_address","value":"terra1n234trhxyj4ze95td2t5ngdpyqd8529urm54epum3aqg3205pcasg0g5pu"}]},{"type":"message","attributes":[{"key":"action","value":"/cosmwasm.wasm.v1.MsgExecuteContract"},{"key":"module","value":"wasm"},{"key":"sender","value":"terra1x46rqay4d3cssq8 …
```
=> fix: Generated clients should use PascalCase.

README.md, package-lock.json, package.json, src/commands/contract/instantiate.ts, src/commands/deploy.ts, src/lib/flag.ts
Allowing for the signer of a deploy or instantiate command to be the default admin of the contract.  Removed the --set-signer-as-admin flag and updated README accordingly.
=> feat:default-admin

src/TerrainCLI.ts, src/commands/sync-refs.ts, src/commands/task/new.ts, src/commands/test.ts
Adding process.exit() command to TerrainCLI.error() and removing instances of the two commands being used sequentially.
Utilizing path.join() to combine paths in sync-refs in place of template literal.
=> fix: TerrainCLI.error()

src/commands/contract/build.ts, src/commands/contract/instantiate.ts, src/commands/contract/optimize.ts, src/commands/contract/store.ts, src/commands/test.ts, src/lib/deployment.ts, src/lib/runCommand.ts
Run the following commands anywhere inside a terrain app:
terrain contract:build
terrain contract:optimize
terrain contract:store
terrain contract:instantiate
Error handling inside of the `instantiate` function to do with a user attempting to instantiate a contract that is not yet deployed on a specified network.
Added execution path in warning at the end of `runCommand`.  The path may be useful to the user just in case a file or directory may have been accidentally moved, renamed, or deleted.
=> feat: run terrain:contract commands anywhere

src/commands/console.ts, src/commands/deploy.ts, src/commands/sync-refs.ts, src/lib/signer.ts
Run the following Terrain commands in any Terrain project subdirectory:
`terrain console`
`terrain deploy`
`terrain sync-refs`
Note:
`terrain test` has already been implemented in a prior PR.
`terrain new` is already a universal command!
=> feat: run main commands anywhere

README.md, src/commands/contract/generateClient.ts, src/commands/contract/migrate.ts, src/commands/contract/new.ts, src/commands/contract/updateAdmin.ts
Run the following Terrain commands in any Terrain project subdirectory:
`terrain contract:generateClient`
`terrain contract:migrate`
`terrain contract:new`
`terrain contract:updateAdmin`
Note:
The following commands have already been updated in the original `feat: run contract commands anywhere` PR.
`terrain contract:build`
`terrain contract:optimize`
`terrain contract:store`
`terrain contract:instantiate`
=> feat: run contract commands anywhere 2

src/TerrainCLI.ts, src/commands/contract/build.ts, src/commands/contract/generateClient.ts, src/commands/contract/instantiate.ts, src/commands/contract/optimize.ts, src/commands/contract/store.ts, src/commands/sync-refs.ts, src/commands/task/new.ts, src/commands/task/run.ts, src/commands/test.ts, src/commands/wallet/new.ts, src/lib/deployment.ts, src/lib/runCommand.ts, src/lib/signer.ts
Updating TerrainCLI styling to include stylized, boxed terminal messages.  TerrainCLI logs will now require the user to provide a message as well as a title for presentation.  Furthermore, the user can surround important information with double quotes so that it may be highlighted in a different color.  Example:
`TerrainCLI.error('Contract "${args.contract}" has not been deployed to the "${args.network}" network', 'Contract Not Deployed');`
=> style: TerrainCLI

src/TerrainCLI.ts, src/commands/console.ts, src/commands/contract/build.ts, src/commands/contract/generateClient.ts, src/commands/contract/instantiate.ts, src/commands/contract/migrate.ts, src/commands/contract/optimize.ts, src/commands/contract/updateAdmin.ts, src/commands/deploy.ts, src/commands/task/new.ts, src/commands/task/run.ts, src/commands/test.ts, src/lib/defaultErrorCheck.ts, src/lib/deployment.ts, src/lib/runCommand.ts
Created a defaultErrorCheck function which is imported to each file that uses `Contract Not Found` errors and replaced them.  Evaluated setting defaultErrorCheck as the default for errorCheck in the runCommand function, however, each command utilizes their own contract name, which will have to be passed to the function directly.
Updated TerrainCLI calls to adhere to updated styling functionality.
Updated variable highlighting regex to be non-greedy to allow for highlighting of multiple vars.
=> feat: default error check

src/commands/deploy.ts
The `--build-schema` flag was removed from the `terrain contract:generateClient` command as the `cargo schema` command is executed upon `terrain contract:build` command execution.  In this PR, I am removing this flag from being passed when calling the `generateClient` command from `deploy`.
=> fix: build schema flag removal

src/commands/new.ts
Retaining silent npm logs and warnings while surfacing any errors that occur.
=> fix: surface npm errors

README.md, src/commands/contract/new.ts
Version `1.0-beta6` of the [CosmWasm/cw-template](https://github.com/CosmWasm/cw-template) throws an error when you attempt to deploy with Terrain.  The issue is with the setup of `CustomError` in the `src/error.rs` directory.  This PR pulls the template from the [9fa5b9b38fca4f99239ac28be48a6e1f0a4d30c8 commit hash](https://github.com/CosmWasm/cw-template/commit/9fa5b9b38fca4f99239ac28be48a6e1f0a4d30c8) which is directly after the [latest version release commit hash](https://github.com/CosmWasm/cw-template/commit/c771646bac6aed25741478984dc902f20d00881e).  This commit only contains the update to `CustomError` which allows Terrain to deploy the template contract without error.
=> fix: cw-template version
